name: CI/CD

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup .net core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: install lambda tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      
      - name: build and test
        run: dotnet test
        working-directory: ./ServiceStackLambda.Tests
        
      
      - name: Create serverless file from template
        uses: danielr1996/envsubst-action@1.1.0
        env:
          DEPLOY_S3_BUCKET: lamda-bucket123
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          input: ServiceStackLambda/aws-lambda-tools-defaults.json
          output: ServiceStackLambda/aws-lambda-tools-defaults.json

      - name: aws login
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: deploy serverless
        run: dotnet lambda deploy-serverless --template serverless.template
        working-directory: ./ServiceStackLambda
